services:
    webapi:
        image: jwl0515/webapi:0.0.1
        ports:
         - 7284:8081
        volumes:
         - ./WebApi/DogProductDb.db:/app/DogProductDb.db
         - ./WebApi/AppUserDb.db:/app/AppUserDb.db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/Certificates/aspnetapp.pfx

    client:
        image: jwl0515/client:0.0.1
        ports:
            - 4200:4200

       
    